// @ts-check
/**
 * Vite just generate the bundle, Type declarations are generated by *tsc*,
 * see "build" script in package.json
 */
import { defineConfig } from "vite";
import tsconfigPaths from "vite-tsconfig-paths";
import { visualizer } from "rollup-plugin-visualizer";
import dts from "vite-plugin-dts";
import { resolve, join } from "path";

export default defineConfig(({ command }) => {
  return {
    clearScreen: false,
    plugins: [
      tsconfigPaths(),
      dts({
        // rollupTypes: true,
        compilerOptions: {
          declarationMap: true,
        },
        include: ["src/shared/**/*"],
        outDir: "dist",
      }),
      process.env.STATS ? visualizer({ filename: "stats.html", emitFile: true }) : [],
    ],
    resolve: {
      preserveSymlinks: true,
    },
    // root: join(__dirname, "src"),

    build: {
      outDir: join(__dirname, "dist/shared"),
      emptyOutDir: true,
      lib: {
        entry: {
          // The dev-client is using Vite's import.meta.env.DEV so we bundle it using tsup, not Vite
          components: resolve(__dirname, "src/shared/components/index.ts"),
          "component-utils": resolve(__dirname, "src/shared/components/utils/index.ts"),
          "shadow-polyfill": resolve(__dirname, "src/shared/components/polyfills/shadow-polyfill.ts"),
          attributes: resolve(__dirname, "src/shared/attributes.ts"),
          datasources: resolve(__dirname, "src/shared/datasources.ts"),
          "dynamic-css": resolve(__dirname, "src/shared/dynamic-css.ts"),
          zod: resolve(__dirname, "src/shared/zod.ts"),
          settings: resolve(__dirname, "src/shared/settings.ts"),
        },
        formats: ["es"],
      },
      rollupOptions: {
        // make sure to externalize deps that shouldn't be bundled
        // into your library
        external: ["zod", "tailwindcss", "jsdom", "vite", "vite-tsconfig-paths", "@enpage/style-system"],
        output: {
          // Provide global variables to use in the UMD build
          globals: {
            zod: "zod",
            tailwindcss: "tailwindcss",
          },
        },
      },
    },
  };
});
