/**
 * Vite just generate the bundle, Type declarations are generated by *tsc*,
 * see "build" script in package.json
 */
import { PluginOption, defineConfig } from "vite";
import tsconfigPaths from "vite-tsconfig-paths";
import { resolve } from "path";
import { visualizer } from "rollup-plugin-visualizer";
import dts from "vite-plugin-dts";

export default defineConfig({
  plugins: [
    tsconfigPaths(),
    dts({ rollupTypes: true }),
    visualizer({ filename: "stats.html", emitFile: true }) as PluginOption,
  ],
  resolve: {
    preserveSymlinks: true,
  },
  build: {
    sourcemap: true,
    emptyOutDir: true,
    lib: {
      // Could also be a dictionary or array of multiple entry points
      entry: {
        index: resolve(__dirname, "src/index.ts"),
        components: resolve(__dirname, "src/components/index.ts"),
        datasources: resolve(__dirname, "src/datasources.ts"),
        "dev-utils": resolve(__dirname, "src/dev-utils.ts"),
      },

      name: "Enpage",
      // the proper extensions will be added
      // fileName: (format, entryName) => `${entryName}.${format}.js`,
      formats: ["es"],
    },
    rollupOptions: {
      // make sure to externalize deps that shouldn't be bundled
      // into your library
      external: ["zod", "tailwindcss", "zod-schema-faker"],
      output: {
        // Provide global variables to use in the UMD build
        globals: {
          zod: "zod",
          tailwindcss: "tailwindcss",
        },
      },
    },
  },
});
