/**
 * Vite just generate the bundle, Type declarations are generated by *tsc*,
 * see "build" script in package.json
 */
import { PluginOption, defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import tsconfigPaths from "vite-tsconfig-paths";
import { resolve } from "path";
import { visualizer } from "rollup-plugin-visualizer";
import dts from "vite-plugin-dts";

export default defineConfig({
  plugins: [
    tsconfigPaths(),
    react(),
    dts(),
    visualizer({ filename: "stats.html", emitFile: true }) as PluginOption,
  ],
  resolve: {
    preserveSymlinks: true,
  },
  build: {
    sourcemap: true,
    emptyOutDir: true,
    lib: {
      // Could also be a dictionary or array of multiple entry points
      entry: resolve(__dirname, "src/index.ts"),
      name: "Enpage",
      // the proper extensions will be added
      fileName: (format) => `enpage-sdk.${format}.js`,
      formats: ["es", "umd"],
    },
    rollupOptions: {
      // make sure to externalize deps that shouldn't be bundled
      // into your library
      external: [
        "zod",
        "react",
        "react/jsx-runtime",
        "react-dom",
        "react-icons",
        "tailwindcss",
      ],
      output: {
        // Provide global variables to use in the UMD build
        globals: {
          react: "React",
          "react/jsx-runtime": "jsx",
          "react-dom": "ReactDOM",
          "react-icons": "ReactIcons",
          zod: "zod",
          tailwindcss: "tailwindcss",
        },
      },
    },
  },
});
