/**
 * Vite just generate the bundle, Type declarations are generated by *tsc*,
 * see "build" script in package.json
 */
import { PluginOption, defineConfig } from "vite";
import react from "@vitejs/plugin-react";
// import { vanillaExtractPlugin } from "@vanilla-extract/vite-plugin";
import tsconfigPaths from "vite-tsconfig-paths";
import { resolve } from "path";
import { visualizer } from "rollup-plugin-visualizer";

export default defineConfig({
  plugins: [
    tsconfigPaths(),
    react(),
    visualizer({ emitFile: true }) as PluginOption,
  ],
  build: {
    sourcemap: "inline",
    lib: {
      // Could also be a dictionary or array of multiple entry points
      entry: resolve(__dirname, "src/index.ts"),
      name: "Enpage",
      // the proper extensions will be added
      fileName: "enpage",
      formats: ["es"],
    },
    rollupOptions: {
      // make sure to externalize deps that shouldn't be bundled
      // into your library
      external: [
        "zod",
        "react",
        "react/jsx-runtime",
        "react-dom",
        "tailwindcss",
        "polished",
        "@vanilla-extract/css",
        "rainbow-sprinkles",
      ],
    },
  },
});
