name: Run tests

on:
  workflow_call:
  push:
    branches: [main]
    # do not trigger CI on tags, it will be handled by the "release" event
    tags-ignore:
      - "*"
    paths:
      - "!.changeset/**"
      - "!.vscode/**"
      - "!docs/**"
      - '**/*.html'
      - '**/*.js'
      - '**/*.ts'
      - '**/*.jsx'
      - '**/*.tsx'
      - '**/*.mjs'
      - '**/*.mts'
      - '**/*.yml'
      - '**/*.yaml'
      - '**/*.json'
  pull_request:
    branches: [main]
    paths:
      - "!.changeset/**"
      - "!.vscode/**"
      - "!docs/**"
      - '**/*.html'
      - '**/*.js'
      - '**/*.ts'
      - '**/*.jsx'
      - '**/*.tsx'
      - '**/*.mjs'
      - '**/*.mts'
      - '**/*.yml'
      - '**/*.yaml'
      - '**/*.json'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  pull-requests: write

env:
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}

jobs:
  test:
    if: ${{ !contains(github.event.head_commit.message, 'chore(release):') }}
    name: Test job
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 8
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.tool-versions'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: build
        run: pnpm build

      - name: lint
        run: pnpm ci:lint

      - name: test
        run: pnpm test

